// Fonts
import { Goldman, Geist_Mono } from "next/font/google";

// Styles
import "@/css/globals.css";
import "@/css/colors.css";

const goldman = Goldman({
  variable: "--font-goldman",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Speed Sync",
  // description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${goldman.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
